version: "3.8"
networks:
  zabbix-network:
    driver: bridge

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:6.4.9-alpine
    container_name: zabbix-server
    restart: unless-stopped
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw
      - ./.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
      - ./.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
      - ./.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          cpus: "0.5"
          memory: 2048M
    env_file:
      - ./env_vars/.env_db_pgsql
      - ./env_vars/.env_srv
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      - postgres-server

  zabbix-web-apache-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:6.4.9-alpine
    container_name: zabbix-web
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "8443:8443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
      - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    env_file:
      - ./env_vars/.env_db_pgsql
      - ./env_vars/.env_web

  postgres-server:
    container_name: zabbix-db
    image: postgres:13.5-alpine3.15
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "zabbix"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    env_file:
      - ./env_vars/.env_db_pgsql
    volumes:
      - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw
      - ./.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
      - ./.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
      - ./.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro

secrets:
  POSTGRES_USER:
    file: ./env_vars/.POSTGRES_USER

  POSTGRES_PASSWORD:
    file: ./env_vars/.POSTGRES_PASSWORD
